### ISSUE TITLE
Don't export PodConfig.ID and ContainerConfig.ID

### ISSUE THREAD

**Issue by jodh-intel** [containers/virtcontainers#171]
These fields should be private.

See: https://github.com/containers/virtcontainers/pull/163#discussion_r107728116.

**Comment by sboeuf** [comment]
@sameo @jodh-intel Having a second thought at this issue, there is no point in implementing this I think. Virtcontainers is not supposed to generate pod/containers IDs. It is supposed to come from the runtime implementation using virtcontainers. In case of virtc, we want to generate this from virtc.
I think we could close this issue because if we set those fields as private, we have no way to set the pod ID (unless we add a new setter function, but I don't see the point while PodConfig is supposed to describe the configuration).
Let me know your thoughts on this one.

**Comment by sameo** [comment]
@sboeuf I think you're right, yes. The pod or container IDs will typically come from the runtime or the orchestration engine (CRI), and we actually should not generate them.
My https://github.com/containers/virtcontainers/pull/163#discussion_r107728116 was partially wrong, sorry about that @jodh-intel. We still want to verify the validity of the IDs we get and they should either be plain `UUID`s or comply with Docker's [stringid](https://github.com/docker/docker/blob/master/pkg/stringid/stringid.go) strings.

**Comment by sboeuf** [comment]
Ok thanks for confirmation. We can close this one.
