### ISSUE TITLE
add generic volume handling

### ISSUE THREAD

**Issue by egernst** [containers/virtcontainers#308]
Appears that append-volumes assumes 9p today.  Volumes is a method for passing a generic device into the container.  ie: docker run -v /dev/vfio/17:/dev/vfio/17.

It doesn't appear to be generic today:
https://github.com/containers/virtcontainers/blob/e01ebd015f77b3e822b597088e6efc102a7e6d9a/qemu.go#L177

**Comment by sboeuf** [comment]
Yes you're right, it is not generic as it is tied to 9pfs.

**Comment by egernst** [comment]
example of how it should work:  $ sudo docker run --runtime=runc -v /dev/vfio/17:/dev/example -it alpine sh
/ # ls /dev/example
/dev/example

And, in the config.json, this is described as:
root@sriov-2:/home/sriov/go/src/github.com/01org/cc-oci-runtime# cat /var/run/docker/libcontainerd/7b94fe6ccdf5304b4cf74c18ebed880cfe580d421820c54b140d251a60a08a09/config.json | python -mjson.tool | grep -b10 -a10 vfio
50490-                "nodev"
50514-            ],
50529-            "source": "mqueue",
50561-            "type": "mqueue"
50590-        },
**50601-        {
50611-            "destination": "/dev/example",
50654-            "options": [
50679-                "rbind"
50703-            ],
50718:            "source": "/dev/vfio/17",
50756-            "type": "bind"
50783-        },**
50794-        {
50804-            "destination": "/etc/resolv.conf",
50851-            "options": [
50876-                "rbind",
50901-                "rprivate"
50928-            ],
50943-            "source": "/var/lib/docker/containers/7b94fe6ccdf5304b4cf74c18ebed880cfe580d421820c54b140d251a60a08a09/resolv.conf",
51072-            "type": "bind"

**Comment by egernst** [comment]
@sboeuf - can you comment on the relevance of this issue, given all the changes that are being introduced currently for Kata?

**Comment by sboeuf** [comment]
Wondering if this is relevant since the --device is handled but not through this way. I think we should not think at volumes the same way docker does. What I mean is that this method `appendVolume()` is the 9pfs method for qemu, which is fine since we use hotplugDevice() if we have a volume presented as a device.

**Comment by amshinde** [comment]
@sboeuf I think it is worth handling this for volumes as well. If the volume directory is mounted ar a location that is backed by a block device, it would make sense to pass the block device and mount it to the desired location within the container.

**Comment by sboeuf** [comment]
@amshinde yes this makes sense.

**Comment by sboeuf** [comment]
After discussion with @amshinde on this issue, I think we should honor `--volume` option by following those steps:
- Detect if the volume passed (translated as a `Mount` inside virtcontainers) is a simple directory, or a device.
- According to the device type (we handle only `BlockDevice` now), we would hotplug it through the VM.
- We would need to modify the `Mount` entry for both the `Type` and the `Destination`. The `Type` being used as the flag to let the agent implementation what to do with it, that is adding a new `Storage` in case of Kata. And the `Destination` being used as the mount point inside the VM.

This way, the volume would be hotplugged as a block device, then found by the block device storage handler inside the agent, and bind mounted by libcontainer into the container.
This would allow for a slightly different result than using `--device` for the same block device because this device would be bind mounted inside the container instead of being recreated using `mknod` relying on `major`/`minor` numbers.
