### ISSUE TITLE
qemu: Detect VMM environment to apply specific flags to our VM

### ISSUE THREAD

**Issue by sboeuf** [containers/virtcontainers#342]
When Clear Containers runs on Azure, it actually runs inside an existing VM (nested VM) managed by Hyper-V hypervisor. And because KVM has some issues when running on a VMM, the only way to get Clear Containers working is to fallback from virtio 1.0 to a previous version, and to disable pmu.
We need to implement a way to detect VMM environment and enable/disable specific flags accordingly.

**Comment by mcastelino** [comment]
@sboeuf this is actually the bug is in KVM. KVM uses the instruction length from the VMExit info to skip the fast MMIO instructions. This is *incorrect* and needs a fix in KVM. So we should add code in our runtime to detect if we are running on top of a VMM and disable virtio 1.0 on such configurations.

Once KVM has the fix, we should no longer need the workaround.

This could also explain the failure on VMWare.

Note: This bug is present even on bare metal, but we get lucky that the CPU does report the instruction length even though there is no assurance from hardware that the instruction length is valid. So if we want to be paranoid we can switch off virtio-io till the kvm bug is fixed.

The bug lies in kvm in the following code
```
static void skip_emulated_instruction(struct kvm_vcpu *vcpu)
{
        unsigned long rip;

        rip = kvm_rip_read(vcpu);
        rip += vmcs_read32(VM_EXIT_INSTRUCTION_LEN);
        kvm_rip_write(vcpu, rip);

        /* skipping an emulated instruction also counts */
        vmx_set_interrupt_shadow(vcpu, 0);
}
```

As per Intel SDM Section 24.2.4 The instruction length is not valid for EPT violations.
