### ISSUE TITLE
Networking: Do not scan the network interfaces in the namespace in hyperstart.go

### ISSUE THREAD

**Issue by mcastelino** [containers/virtcontainers#418]
We scan the network namespace twice in the case of CNM. Once once the pre-hook returns and the second time in hyperstart.go.

This is done to handle the CNI case where the spec does not return the MTU of the network interface.
https://github.com/containernetworking/cni/blob/master/SPEC.md#result

We do not scan the network ns in the case of CNI as we rely on the result field.
We should scan the network ns even in the case of CNI as the namespace may change later due to the changes we may need to make to connect the network to the VM.

**Comment by mcastelino** [comment]
https://github.com/containernetworking/cni/issues/513

**Comment by sboeuf** [comment]
@mcastelino several comments about this issue. I agree I would prefer not to scan several times the network namespace, it could save us some time. But right now, because we are relying on the `Result` type from CNI package, even in case of CNM implementation, hyperstart needs to read again because the results does not carry the MTU info.
I have seen the comment about the issue you've opened on CNI repo, and I wonder if we should not move to our own `NetworkResult` structure so that we can have all the field we want without having to justificate everything and battle for a new field. @sameo what do you think about us defining our own Result structure ? Also, I think it could help us to simplify the translation into Hyperstart fields. And we could follow that by moving the network scan to the network interface level (I am suggesting that we don't rely on specific return from CNI but scan whatever network plugin we're using).

**Comment by mcastelino** [comment]
@sboeuf yes we should define our own results structure that embeds the CNI struct. We need more information than what CNI provides. Also I would to scan upfront and populate this struct vs scanning later. We should however retain what the CNI plugin returns as it may contain information we may not be able to obtain via scanning easily.

Once we have support for things like SRIOV and vhost-user this scanning in hyper start will not work anyway. I had to hack up the macvtap implementation also due to this issue.

**Comment by amshinde** [comment]
@mcastelino @sboeuf Just to add here, for the SRIOV case,  I am fetching the MTU info the first time the network namespace is scanned. Physical endpoints are simply ignored during the second scan, as they are not even available in the namespace after being assigned to the VM.

**Comment by sameo** [comment]
@mcastelino @sboeuf It makes perfect sense to define our own networking result structure and include the CNI `Result` data in it.

**Comment by mcastelino** [comment]
@sboeuf with anonymous struct fields we will not be bound to the CNI results struct. If we do go away from the CNI result struct the dependent code will not change as long as the field names are retained.

@amshinde do you want to make this change or should I?

**Comment by sboeuf** [comment]
@mcastelino I am actually working on this change.

**Comment by mcastelino** [comment]
@amshinde I recollect that in your VFIO PR also you have some code in the rescan. So this PR may change/simplify your code also.

**Comment by sboeuf** [comment]
@mcastelino https://github.com/containers/virtcontainers/pull/470

**Comment by egernst** [comment]
@amshinde @sboeuf   Fixed via #470.
