### ISSUE TITLE
VFIO devices need to be hotplugged .

### ISSUE THREAD

**Issue by amshinde** [containers/virtcontainers#444]
We need to move towards hot-plugging all devices passed with --device. 
VFIO devices are currently cold-plugged, once we resolve the issues around hot-plugging vfio devices, we need to call attachDevices() after VM is launched to hotplug all devices.

**Comment by amshinde** [comment]
cc @mcastelino

**Comment by devimc** [comment]
I implemented a new class to hot plug devices (Bridge [1]), could you please try to hot plug vfio devices using this class?

[1] - https://github.com/devimc/runtime/commit/a3da674b9eda08eb170a8837c297fe09a9830837#diff-8dddcab27acff41f4ab0d41ff4272253

**Comment by amshinde** [comment]
@devimc There are performance issues with hotplugged vfio devices that need to be fixed first.

**Comment by sameo** [comment]
@amshinde Could you please elaborate on the issues we're seeing ?

**Comment by mcastelino** [comment]
@amshinde @sameo @devimc this peformance is related to vfio and not really hotplug. When nvdimm is enabled the VM takes a long time to bootup. This bug is being investigates. This is a nvdimm and vfio interaction issue. VFIO needs the memory to be pinned (except the nvdimm memory). And the issue lies with qemu trying to pin nvdimm memory.

**Comment by amshinde** [comment]
Closing this, as this has been fixed.
