### ISSUE TITLE
Rework of the proxy interface

### ISSUE THREAD

**Issue by sboeuf** [containers/virtcontainers#518]
With both `cc-proxy`, `kata-proxy` and the `no-proxy` cases, I have been thinking that our current `proxy` interface does not meet all the needs for those different cases...
First I think we don't need to return a URL when calling into `connect()` or a list of URL when calling into `register()`, only one URL should be returned by `start()` now that we agreed on the model one proxy per VM. This opinion is based on the fact that a proxy is at a pod/VM level and I don't expect several URLs to be provided to the shim, the same way this shim will connect to only one socket on the VM in case we don't go through a proxy.
Then I think that most of the interface is fine, except `sendCmd()`. I have been turning the problem upside down, but no way to make all the cases work with this. We should agree on what should be a proxy in order to know what to expect from it. I think a proxy has to be accessed the same way we would access the VM directly, that is through a socket. This is already the case for all our different cases, but the problem is about the way the data are processed and are expected to be received by this proxy or directly by the VM. The most generic way I can think of is by sending an array of bytes through the socket opened through the `connect()`. This would suggest that `connect()` would actually return a handler to this socket connection. We should get rid of the `sendCmd()` because it assumes the agent to know about the kind of proxy that is going to be used, while a pure array of bytes sent through the provided socket would be processed either by the proxy or directly by the agent, transparently for virtcontainers. Indeed, we should use this generic socket handler from the agent implementation in order to call into some specific functions (specific to the agent protocol) but always requiring a socket to communicate to.
All what I am suggesting here would be pretty straight forward to implement for both `kata-proxy` and `no-proxy` since they follow this model of receiving the same data, the encapsulation being done by the proxy itself if needed.
But this would require some extra work for our current `cc-proxy` and `cc_proxy.go` implementation since the encapsulation is done by the client itself.
One first step to avoid too much changes would be to consider using the `sendCmd()` the way it is right now, only for the `cc-proxy` case, while we would not use it for other new implementations. Instead, we would only use the subset `start()`, `register()`, `unregister()`, `connect()`, `disconnect()`.
This is the first time we're really testing the flexibility of virtcontainers interfaces, and I would like to make sure we move in the right direction by refining them in case we see a need for that. And I think this is the case here.

@sameo @jodh-intel WDYT ?

**Comment by sameo** [comment]
Assuming we want to completely drop the single proxy model (Which I think we should, the HA and upgrade complexities linked to it are too big imo), we could simplify the current interface even further. We should change our logic so that the shim and the runtime only ever talk to the agent, or a URL that looks like an agent endpoint:

* `start()`: Starts the proxy binary and here we need to give the proxy 2 pieces of information: Which endpoint (socket, etc...) it should listen on and where and how it should connect to the VM/Pod. As @sboeuf points out, `start` would now only return a URL for the shim to reach the VM/Pod.
* `register()`/`unregister()`: Those 2 become almost pointless. Why do we need to register a VM/Pod when we know we're only going to handle a single one? The only case where this might be needed is when/if we want to start the proxy before we even know anything about the VM and we need to asynchronously let the proxy know about a new VM. So if we want to keep those around, we need to make them simple notifications, i.e. they should only return an error and nothing else.
* `connect()`\`disconnect()`: This one can be removed. `start()` returns a URL and this should be sufficient for anyone that wants to connect to a proxy to know how it should do it. We could provide a `agent.URL` method for getting 
* `sendCmd()` is only used by the agent implementations to, well, send commands into the VM. `kata_agent` should not use `sendCmd()` at all, so this would only be used by `cc_proxy`. An agent should only have to know about the protocol used by the agent, and a shim ideally would only talk to an agent as well.

All in all I think a vc **2.0.0** proxy interface could be simplified down to:

```Go
// proxy is the virtcontainers proxy interface.
type proxy interface {
	start(pod Pod) (string, error)
        stop(pod Pod) (error)

        register(pod Pod) (error)
 }
```

Now this would be a **2.0.0** and it would mean large changes to our current `cc_proxy` and `hyperstart_agent` code.

So I propose we go through the following steps:

1) Keep the current proxy interface and for kata_proxy this would mean:
- `sendCmd`, `register` and `unregister` are NO-OPs
- I believe `connect` and `disconnect` should be NO-OP as well, although it would be easily implementable (only the returned URL would really matter).

2) Implement a 2.0.0 proxy interface based on the above interface:
- Many parts of the code would be simplified as we would no longer need to register our VMs, nor we'd need to connect to a VM before interacting with it.
- kata_proxy would be left almost unmodified (except for getting rid of the NO-OPs)
- cc_proxy would have to go through some fairly heavy changes.

Does that make sense?

**Comment by sboeuf** [comment]
It does really make sense ! And I agree this has to be a 2 steps thing since we want to make sure we can make both `cc-proxy`, `kata-proxy` and `no-proxy` working before we decide to bring those heavy changes to `cc-proxy`.

**Comment by sboeuf** [comment]
As a side note here, I have been thinking about this proxy interface 2.0. The changes for the `cc-proxy` could be simplified if we were listening on two different sockets with the proxy. We would have one URL that we would provide to the shim and runtime, and this would be used for all the things specific to the `shim <==> proxy` protocol, while the agent implementation `hyperstart.go` would send hyperstart frames directly to a new socket created by the proxy and dedicated to multiplex the frames with the hyperstart agent.
Or another solution would be to drop the shim/proxy protocol so that the proxy would actually behave the same way the agent would behave if we were directly connected to it.
The whole issue here relies on the fact that we want our agent to talk the same protocol, in both cases where we would have a proxy or not. But the fact that our `cc-proxy` has its own protocol actually prevents us from that.

**Comment by sboeuf** [comment]
Another note after some discussions with @sameo. The proxy should not be considered as a distinct component of Clear Containers, but instead, it should be a sub-component of the agent. This would simplify virtcontainers, allowing every agent implementation to call into the right proxy implementation. The definition of a proxy is a simple abstraction layer needed in case the agent cannot handle the multiplexing of several processes.

**Comment by sboeuf** [comment]
@jodh-intel @sameo I would like to modify `cc-proxy` binary and I would like that we agree on what I should do here to achieve this.
I can see 2 distinct options here:
- We could implement hyperstart protocol in `cc-proxy`. This means we would have to modify `hyperstart_agent.go` to send hyperstart protocol command directly. The different command would be deciphered from the proxy, then would be modified in order to include the sequence IDs. Indeed, `cc-proxy` is not a dumb piece of code because part of the commands need to be slightly modified.
The pros are: real support for an architecture without proxy.
The cons are: Involve lots of work and code duplication about the handling of the hyperstart protocol (this is supposed to be handled from the agent already). Not really compliant since we expect one socket to communicate with the agent (regardless of the proxy). I mean we would use one socket to talk with the proxy, but we should use 2 sockets if we were directly talking to the agent.
- We could move the code from `cc_proxy.go` to `hyperstart_agent.go`. This means we don't expect it is possible to talk directly to the agent from the runtime, which is okay IMO since the hyperstart protocol is not properly designed to support with/without proxy cases.
The pros are: seems easy to implement and the `cc-proxy` binary would not need any changes.
The cons are: we assume Clear Containers case will always use the cc-proxy, and we won't try to support a case where `hyperstart_agent.go` could directly talk to the agent.

Both cases would allow for a simpler proxy interface, with no need for a `sendCmd()` function.

I really prefer the second option because it will be easy to implement and we won't break what we have already. We will only decide to tie the `hyperstart_agent.go` to a specific proxy `cc-proxy`. We would be okay to call into `cc-proxy` specific protocol, instead of a pure hyperstart one.

After such a change, I think we could reduce the virtcontainers proxy interface to its most simple form:
```go
// proxy is the virtcontainers proxy interface.
type proxy interface {
	start(pod Pod) (string, error)
        stop(pod Pod) (error)
}
```
